# planning spec for a demo trajectory.
# see a6data.py
# Author: Conor Hayes

# trajectory type.
traj_type = 'SCREW_CUBIC'

# duration of motion in seconds
duration_s = 5.0

# actual initial joint configuration (radians)
actual_init_config = [0, 0, 0, 0, 0, 0]


[Ts_start]
SE3 = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
]


[Ts_end]
SE3 = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
]