# planning spec for a demo trajectory.
# see a6data.py
# Author: Conor Hayes

# trajectory type.
traj_type = 'SCREW_CUBIC'

# duration of motion in seconds
duration_s = 5.0

# actual initial joint configuration (radians)
actual_init_config = [0, 0, 0, 0, 0, 0]


[Ts_start]
SE3 = [
    [0.170,0.905,-0.391,0.346],
    [0.572,0.232,0.786,0.396],
    [0.802,-0.358,-0.478,-0.491],
    [0,0,0,1]
]

[Ts_end]
SE3 = [
    [-0.805,0.593,-0.022,-0.533],
    [-0.110,-0.185,-0.977,0.029],
    [-0.584,-0.783,0.214,-0.361],
    [0,0,0,1]
]